### PR TITLE
Update for Matrix and add CI

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR imports CI configuration from game.libretro and updates the code for Matrix. The version is bumped to 0.0.5.

## How has this been tested?

I've tested the code updates on my `retroplayer-19alpha1` branch with no issues. CI is untested

### CODE REVIEW

**Comment by garbear** [comment]
CC @VelocityRa

**Review by VelocityRa — APPROVED** [review]
Cool.
We'll have to test CI after it's merged?

**Comment by garbear** [comment]
@AlwinEsch Is there any CI we can set up until https://github.com/garbear/xbmc/pull/86 gets upstreamed?

**Comment by AlwinEsch** [comment]
I connected Azure, this automatically generated a request here https://github.com/kodi-game/game.shader.presets/pull/3
Think if this request is forced, Azure should also come in it.

Unfortunately, I have no rights because of Jenkins and Travis. With Jenkins, @lrusak could help.

**Comment by lrusak** [comment]
@garbear @AlwinEsch jenkins has been added to your party

**Comment by lrusak** [comment]
```
In file included from /home/jenkins/workspace/binary-addons/kodi-android-aarch64-Matrix/tools/depends/target/binary-addons/game.shader.presets/src/addon.cpp:22:

/home/jenkins/workspace/binary-addons/kodi-android-aarch64-Matrix/tools/depends/target/binary-addons/game.shader.presets/src/addon.h:23:10: fatal error: 'kodi/addon-instance/ShaderPreset.h' file not found

#include <kodi/addon-instance/ShaderPreset.h>

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.
```

**Comment by garbear** [comment]
The mentions of `xbmc/xbmc.git` in this PR should be `kodi-game/xbmc.git`. Will update

**Comment by garbear** [comment]
Updated. Does it work now?

**Comment by lrusak** [comment]
jenkins only knows about xbmc/xbmc.git (Leia, Matrix) so if you need to use another repo that may not work properly without changes to `xbmc/pipeline-library`

EDIT: I'm not sure what the best solution is for this. We could always disable jenkins until support is ready upstream at xbmc Master?

**Comment by garbear** [comment]
Rebased on https://github.com/kodi-game/game.shader.presets/pull/3

**Comment by garbear** [comment]
CI succeeds on Win32/Win64/Linux! This is the expanse of systems we've tested this on. Let's merge now and sort out the other platforms next.

Current failues:

### Jenkins

Fails because `buildPlugin(version: "Matrix")` pulls in master, but we need branch `retroplayer-19alpha2` at kodi-game.

### Travis

Same failure I think, even though `.travis.xml` is set to pull `retroplayer-19alpha2` from kodi-game/xbmc.

```
In file included from /home/travis/build/kodi-game/game.shader.presets/src/addon.cpp:22:0:
/home/travis/build/kodi-game/game.shader.presets/src/addon.h:23:10: fatal error: kodi/addon-instance/ShaderPreset.h: No such file or directory
#include <kodi/addon-instance/ShaderPreset.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### macOS

Fails with error:

```
[ 13%] Building CXX object CMakeFiles/game.shader.presets.dir/src/log/LogAddon.cpp.o

In file included from /Users/travis/build/kodi-game/game.shader.presets/src/log/LogAddon.cpp:23:
/Users/travis/build/kodi-game/game.shader.presets/src/utils/CommonIncludes.h:23:10: fatal error: 'posix/os-types.h' file not found
#include "posix/os-types.h"
         ^~~~~~~~~~~~~~~~~~

1 error generated.
```

### UWP

Fails with error:

```
Creating library D:/a/1/s/build/game.shader.presets-prefix/src/game.shader.presets-build/Release/game.shader.presets.lib and object D:/a/1/s/build/game.shader.presets-prefix/src/game.shader.presets-build/Release/game.shader.presets.exp

file_path_special.obj : error LNK2019: unresolved external symbol GetModuleHandle referenced in function fill_pathname_abbreviate_special [D:\a\1\s\build\game.shader.presets-prefix\src\game.shader.presets-build\game.shader.presets.vcxproj] [D:\a\1\s\build\game.shader.presets.vcxproj]

D:\a\1\s\build\game.shader.presets-prefix\src\game.shader.presets-build\Release\game.shader.presets.dll : fatal error LNK1120: 1 unresolved externals [D:\a\1\s\build\game.shader.presets-prefix\src\game.shader.presets-build\game.shader.presets.vcxproj] [D:\a\1\s\build\game.shader.presets.vcxproj]

##[error]The process 'C:\Program Files\CMake\bin\cmake.exe' failed with exit code 1
##[error]CMake failed with error: The process 'C:\Program Files\CMake\bin\cmake.exe' failed with exit code 1
```

**Pull request merged**
