### PR TITLE
Import HLSL shader presets

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR replaces the git submodules with the actual files, and only the ones we use.

Git submodules aren't handled by Kodi's build system, and even if they were, we don't want to ship 10s of megabytes of unused shaders.

However, the HLSL shaders aren't really being developed these days, so we can just copy/paste the files directly.

I checked and, in the last 6 years, only a few files have changed. I left the changes as a separate commit in case they need to be inspected.

## Related PRs

Replaces https://github.com/VelocityRa/xbmc/pull/24

## How has this been tested?

Tested with the following commit: [9408b746c1d64c8774abfed9d8ef983257d14781](https://github.com/garbear/xbmc/commit/9408b746c1d64c8774abfed9d8ef983257d14781)

Test builds with this change, and removing the shaders from the xbmc repo, are in progress.

### CODE REVIEW

**Comment by garbear** [comment]
Rebased on https://github.com/kodi-game/game.shader.presets/pull/9. Lets see how CI does.

EDIT: win32 and win64 are good!

**Comment by garbear** [comment]
Good to merge?

**Review by VelocityRa — APPROVED** [review]
Sorry, yeah lgtm.

**Review by gusandrianos — APPROVED** [review]
lgtm as well. Can we do the same for glsl shaders too?

**Comment by garbear** [comment]
This PR replaces https://github.com/VelocityRa/xbmc/pull/24. Did I ever do a similar PR for glsl shaders? If not, you'll have to do the same for glsl what I did here.

**Comment by gusandrianos** [comment]
You didn't. I'll check if the presets aren't updated regularly and if so I'll make a PR similar to this one.

**Pull request merged**
